surenaVgazebo:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 200

    # Position Controllers ---------------------------------------
    joint1_position_controller:
        type: effort_controllers/JointPositionController
        joint: RJ_hip_yaw
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint2_position_controller:
        type: effort_controllers/JointPositionController
        joint: RJ_hip_roll
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint3_position_controller:
        type: effort_controllers/JointPositionController
        joint: RJ_hip_pitch
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint4_position_controller:
        type: effort_controllers/JointPositionController
        joint: RJ_knee_pitch
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : -200
    joint5_position_controller:
        type: effort_controllers/JointPositionController
        joint: RJ_ankle_pitch
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint6_position_controller:
        type: effort_controllers/JointPositionController
        joint: RJ_ankle_roll
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint7_position_controller:
        type: effort_controllers/JointPositionController
        joint: LJ_hip_yaw
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint8_position_controller:
        type: effort_controllers/JointPositionController
        joint: LJ_hip_roll
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint9_position_controller:
        type: effort_controllers/JointPositionController
        joint: LJ_hip_pitch
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint10_position_controller:
        type: effort_controllers/JointPositionController
        joint: LJ_knee_pitch
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : -200
    joint11_position_controller:
        type: effort_controllers/JointPositionController
        joint: LJ_ankle_pitch
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint12_position_controller:
        type: effort_controllers/JointPositionController
        joint: LJ_ankle_roll
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint13_position_controller:
        type: effort_controllers/JointPositionController
        joint: J_waist_yaw
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint14_position_controller:
        type: effort_controllers/JointPositionController
        joint: J_waist_pitch
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint15_position_controller:
        type: effort_controllers/JointPositionController
        joint: J_waist_roll
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint16_position_controller:
        type: effort_controllers/JointPositionController
        joint: RJ_sh_pitch
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint17_position_controller:
        type: effort_controllers/JointPositionController
        joint: RJ_sh_roll
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint18_position_controller:
        type: effort_controllers/JointPositionController
        joint: RJ_sh_yaw
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint19_position_controller:
        type: effort_controllers/JointPositionController
        joint: RJ_elbow_pitch
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint20_position_controller:
        type: effort_controllers/JointPositionController
        joint: RJ_wrist_yaw
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint21_position_controller:
        type: effort_controllers/JointPositionController
        joint: RJ_wrist_roll
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint22_position_controller:
        type: effort_controllers/JointPositionController
        joint: RJ_wrist_pitch
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint23_position_controller:
        type: effort_controllers/JointPositionController
        joint: LJ_sh_pitch
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint24_position_controller:
        type: effort_controllers/JointPositionController
        joint: LJ_sh_roll
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint25_position_controller:
        type: effort_controllers/JointPositionController
        joint: LJ_sh_yaw
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint26_position_controller:
        type: effort_controllers/JointPositionController
        joint: LJ_elbow_pitch
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint27_position_controller:
        type: effort_controllers/JointPositionController
        joint: JL_wrist_yaw
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint28_position_controller:
        type: effort_controllers/JointPositionController
        joint: LJ_wrist_roll
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
    joint29_position_controller:
        type: effort_controllers/JointPositionController
        joint: LJ_wrist_pitch
        pid: {p: 3000, i: 0.0, d: 20}
        setpoint : 0
